# Generated by Django 4.2.1 on 2023-06-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
