# Generated by Django 4.2.2 on 2023-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
